# Generated by Django 5.1.1 on 2024-10-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="unique_id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="unique_id",
            new_name="uuid",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
            ),
        ),
    ]
