# Generated by Django 5.1.1 on 2024-10-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_stripe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="stripe_image",
        ),
    ]
